name: Devnet - Contracts deployment

on:
  workflow_dispatch:
    inputs:
      network:
        description: Network deploy on
        required: true
        default: devnet
        options:
          - devnet
        type: choice
      token_address:
        description: Already deployed token address
        required: false
        default: "0xE2566cC08913e2d8ECe3517E635335880C1c400a"
        type: string
      rpc_endpoint:
        description: RPC endpoint
        required: false
        default: https://rpc.devnet.archivist.storage
        type: string
      contracts_ref:
        description: "Contracts ref: blank = current branch"
        required: false
        type: string
        default: ''

env:
  NETWORK: ${{ inputs.network }}
  CONTRACTS_REVISION: ${{ inputs.contracts_ref }}
  CONFIG_REPOSITORY: archivist-config
  CONFIG_REPOSITORY_BRANCH: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create access token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOYER_APP_ID }}
          private-key: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ env.CONFIG_REPOSITORY }}

      - name: Checkout contracts repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.contracts_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Deploy contracts
        run: |
            # Deploy
            npm run deploy -- --network "${{ inputs.network }}" --deployment-id "${{ inputs.network }}" --reset

            # Stage deployed_addresses.json and artifacts/*.json
            git add -f ignition/deployments/${{ inputs.network }}/**/*.json ':^ignition/deployments/${{ inputs.network }}/**/*.dbg.json' \
              ':^ignition/deployments/${{ inputs.network }}/journal.jsonl' \
              ':^ignition/deployments/${{ inputs.network }}/build-info'

        env:
          TOKEN_ADDRESS: ${{ inputs.token_address }}
          ARCHIVIST_DEVNET_URL: ${{ inputs.rpc_endpoint }}
          ARCHIVIST_DEVNET_PRIVATE_KEY: ${{ secrets.DEVNET_CONTRACTS_DEPLOYER_PRIVATE_KEY }}
          HARDHAT_IGNITION_CONFIRM_RESET: false
          HARDHAT_IGNITION_CONFIRM_DEPLOYMENT: false

      - name: Commit deployment artifacts
        if: false
        uses: planetscale/ghcommit-action@v0.2.18
        with:
          commit_message: "chore(${{ env.NETWORK }}): marketplace updated\n${{ github.actor }}\n${{ github.ref_type }}: ${{ github.ref_name }}\n${{ github.event_name }}: ${{ github.repository }}\n${{ github.event.head_commit.message || 'triggered manually' }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          repo: ${{ github.repository }}
          branch: ${{ github.event.repository.default_branch }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Set outputs
        id: marketplace
        run: |
          echo "address=$(jq -r '."Marketplace#Marketplace"' "ignition/deployments/${{ inputs.network }}/deployed_addresses.json")" >> $GITHUB_OUTPUT
          echo "abi=$(jq '.abi | tojson' "ignition/deployments/${{ inputs.network }}/artifacts/Marketplace#Marketplace.json")" >> $GITHUB_OUTPUT

      - name: Checkout config repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ env.CONFIG_REPOSITORY }}
          ref: ${{ env.CONFIG_REPOSITORY_BRANCH }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Update config
        run: |
          # Variables
          config="${{ env.NETWORK }}.json"
          config_updated="${{ env.NETWORK }}-updated.json"

          # Functions
          rename_config() {
            mv "${config_updated}" "${config}"
          }

          # .marketplace
          jq -r '.marketplace[].contractAddress |= "${{ steps.marketplace.outputs.address }}"' "${config}" > "${config_updated}" && rename_config
          jq -r '.marketplace[].abi |= ${{ steps.marketplace.outputs.abi }}' "${config}" > "${config_updated}" && rename_config

      - name: Commit updated config
        uses: planetscale/ghcommit-action@v0.2.18
        with:
          commit_message: "chore(${{ env.NETWORK }}): marketplace updated\n${{ github.actor }}\n${{ github.ref_type }}: ${{ github.ref_name }}\n${{ github.event_name }}: ${{ github.repository }}\n${{ github.event.head_commit.message || 'triggered manually' }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          repo: ${{ github.repository_owner }}/${{ env.CONFIG_REPOSITORY }}
          branch: ${{ env.CONFIG_REPOSITORY_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
