name: Devnet - Contracts deployment

on:
  workflow_dispatch:
    inputs:
      network:
        description: Network deploy on
        required: true
        default: devnet
        options:
          - devnet
        type: choice
      token_address:
        description: Already deployed token address
        required: false
        default: "0x7AC8a39172e44e66F719e0960F1Ee965Fe49AC1c"
        type: string
      rpc_endpoint:
        description: RPC endpoint
        required: false
        default: https://rpc.devnet.archivist.storage
        type: string
      contracts_ref:
        description: "Contracts ref: blank = current branch"
        required: false
        type: string
        default: ''

env:
  NETWORK: ${{ inputs.network }}
  ADDRESS_TYPE: latest
  CONTRACTS_REVISION: ${{ inputs.contracts_ref }}
  CONFIG_REPOSITORY: archivist-config
  CONFIG_REPOSITORY_BRANCH: main
  MARKETPLACE_ADDRESS_URL: https://marketplace.archivist.storage

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create access token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOYER_APP_ID }}
          private-key: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ env.CONFIG_REPOSITORY }}

      - name: Checkout contracts repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.contracts_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Deploy contracts
        run: |
            # Deploy
            npm run deploy -- --network "${{ inputs.network }}" --deployment-id "${{ inputs.network }}" --reset

            # Stage deployed_addresses.json and artifacts/*.json
            git add -f ignition/deployments/${{ inputs.network }}/**/*.json ':^ignition/deployments/${{ inputs.network }}/**/*.dbg.json' \
              ':^ignition/deployments/${{ inputs.network }}/journal.jsonl' \
              ':^ignition/deployments/${{ inputs.network }}/build-info'

        env:
          TOKEN_ADDRESS: ${{ inputs.token_address }}
          ARCHIVIST_DEVNET_URL: ${{ inputs.rpc_endpoint }}
          ARCHIVIST_DEVNET_PRIVATE_KEY: ${{ secrets.DEVNET_CONTRACTS_DEPLOYER_PRIVATE_KEY }}
          HARDHAT_IGNITION_CONFIRM_RESET: false
          HARDHAT_IGNITION_CONFIRM_DEPLOYMENT: false

      - name: Commit deployment artifacts
        uses: planetscale/ghcommit-action@v0.2.18
        with:
          commit_message: "chore(${{ env.NETWORK }}): contracts deployment artifacts\n${{ github.actor }}: ${{ github.event.head_commit.message }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          repo: ${{ github.repository }}
          branch: ${{ github.event.repository.default_branch }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Update marketplace address endpoint
        run: |
          # Variables
          network_path="${NETWORK//_/-}"
          marketplace_address=$(jq -r '."Marketplace#Marketplace"' "ignition/deployments/${{ inputs.network }}/deployed_addresses.json")
          echo "${marketplace_address}" > "${{ env.ADDRESS_TYPE }}"

          # Update address
          buckets="${{ secrets.S3_PRIMARY_BUCKET }} ${{ secrets.S3_SECONDARY_BUCKET }}"
          for bucket in ${buckets}; do
            aws s3 cp \
              --acl public-read \
              --content-type "text/plain" \
              ${{ env.ADDRESS_TYPE }} s3://${bucket}/${network_path}/${{ env.ADDRESS_TYPE }}
          done

          # Flush cache
          invalidation_id=$(aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/${network_path}/${{ env.ADDRESS_TYPE }}" | jq -r '.Invalidation.Id')
          aws cloudfront wait invalidation-completed --distribution-id ${{ secrets.DISTRIBUTION_ID }} --id "${invalidation_id}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Check marketplace address endpoint
        run: |
          network_path="${NETWORK//_/-}"
          echo "Marketplace address endpoint: ${{ env.MARKETPLACE_ADDRESS_URL }}/${network_path}/${{ env.ADDRESS_TYPE }}"
          curl -s ${{ env.MARKETPLACE_ADDRESS_URL }}/${network_path}/${{ env.ADDRESS_TYPE }}

      - name: Set outputs
        id: marketplace
        run: |
          echo "address=$(jq -r '."Marketplace#Marketplace"' "ignition/deployments/${{ inputs.network }}/deployed_addresses.json")" >> $GITHUB_OUTPUT
          echo "abi=$(jq '.abi | tojson' "ignition/deployments/${{ inputs.network }}/artifacts/Marketplace#Marketplace.json")" >> $GITHUB_OUTPUT

      - name: Checkout config repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ env.CONFIG_REPOSITORY }}
          ref: ${{ env.CONFIG_REPOSITORY_BRANCH }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Update config
        run: |
          # Variables
          config="${{ env.NETWORK }}.json"
          config_updated="${{ env.NETWORK }}-updated.json"

          # Functions
          rename_config() {
            mv "${config_updated}" "${config}"
          }

          # .marketplace
          jq -r '.marketplace[].contractAddress |= "${{ steps.marketplace.outputs.address }}"' "${config}" > "${config_updated}" && rename_config
          jq -r '.marketplace[].abi |= ${{ steps.marketplace.outputs.abi }}' "${config}" > "${config_updated}" && rename_config

      - name: Commit updated config
        uses: planetscale/ghcommit-action@v0.2.18
        with:
          commit_message: "chore(${{ env.NETWORK }}): marketplace updated\n${{ github.actor }}: ${{ github.event.head_commit.message }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          repo: ${{ github.repository_owner }}/${{ env.CONFIG_REPOSITORY }}
          branch: ${{ env.CONFIG_REPOSITORY_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
